import { useSelector } from "react-redux";
import { motion } from "framer-motion";
import { format } from "date-fns";
import { FiFile, FiDownload, FiMic } from "react-icons/fi";

const MessageBubble = ({ message }) => {
  const { user } = useSelector((state) => state.auth);
  const isMine = message.sender._id === user._id;

  const hasAttachments = message.attachments && message.attachments.length > 0;
  const primaryAttachment = hasAttachments ? message.attachments[0] : null;

  const isAutoGeneratedMediaMsg =
    (message.mediaUrl || hasAttachments) &&
    (message.content === "Voice Message 🎙️" ||
      message.content.startsWith("Shared a photo:") ||
      message.content.startsWith("Shared a video:") ||
      message.content.startsWith("Shared a voice note:") ||
      message.content.startsWith("Shared a file:"));

  const isImageOrVideoOnly =
    (hasAttachments
      ? primaryAttachment &&
        (primaryAttachment.type === "image" ||
          primaryAttachment.type === "video")
      : message.mediaUrl &&
        (message.mediaType === "image" || message.mediaType === "video")) &&
    (isAutoGeneratedMediaMsg || !message.content || !message.content.trim());

  const renderMedia = () => {
    const attachments = hasAttachments
      ? message.attachments
      : message.mediaUrl
        ? [
            {
              url: message.mediaUrl,
              type: message.mediaType,
              fileName: message.content.split(": ").pop() || "File",
            },
          ]
        : [];

    if (attachments.length === 0) return null;

    return (
      <div className="flex flex-col gap-3 w-full">
        {attachments.map((attachment, index) => {
          const { url, type, fileName } = attachment;
          if (!url) return null;

          switch (type) {
            case "image":
              return (
                <div
                  key={
                    attachment.id ||
                    attachment._id ||
                    attachment.public_id ||
                    `att-${message._id}-${index}`
                  }
                  className="relative group overflow-hidden rounded-2xl cursor-pointer shadow-md hover:shadow-lg transition-all border border-slate-200/70 dark:border-white/5"
                  onClick={() => window.open(url, "_blank")}
                >
                  <img
                    referrerPolicy="no-referrer"
                    src={url}
                    alt={fileName || "Shared Attachment"}
                    className="max-w-xs md:max-w-md max-h-72 object-cover rounded-2xl transition-transform duration-300 group-hover:scale-[1.015]"
                  />
                  <div className="absolute inset-0 bg-black/30 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center rounded-2xl">
                    <span className="bg-black/60 text-white text-xs px-3 py-1.5 rounded-full font-bold shadow-md select-none backdrop-blur-sm">
                      Open Original
                    </span>
                  </div>
                </div>
              );
            case "video":
              return (
                <div
                  key={
                    attachment.id ||
                    attachment._id ||
                    attachment.public_id ||
                    `att-${message._id}-${index}`
                  }
                  className="relative overflow-hidden rounded-2xl shadow-md border border-slate-200/70 dark:border-white/5"
                >
                  <video
                    src={url}
                    controls
                    className="max-w-xs md:max-w-md max-h-80 rounded-2xl focus:outline-none bg-black"
                  />
                </div>
              );
            case "audio":
              return (
                <div
                  key={
                    attachment.id ||
                    attachment._id ||
                    attachment.public_id ||
                    `att-${message._id}-${index}`
                  }
                  className="flex flex-col gap-3 p-4 rounded-2xl bg-white/90 dark:bg-[#0c1226]/50 border border-slate-200/70 dark:border-white/5 min-w-[270px] max-w-xs select-none backdrop-blur-md"
                >
                  <div className="flex items-center gap-2.5">
                    <div className="w-9 h-9 rounded-xl bg-rose-500/10 text-rose-500 dark:text-red-400 flex items-center justify-center shrink-0">
                      <FiMic size={16} className="animate-pulse" />
                    </div>
                    <div className="flex flex-col min-w-0 text-left">
                      <span className="text-xs font-bold text-slate-800 dark:text-white">
                        Voice Note
                      </span>
                      <span className="text-[10px] font-bold text-slate-500 dark:text-gray-500 uppercase tracking-wider">
                        Audio Recording
                      </span>
                    </div>
                  </div>
                  <audio
                    src={url}
                    controls
                    className="w-full filter dark:invert text-slate-800 focus:outline-none"
                  />
                </div>
              );
            case "file":
            default:
              const fileDisplayName =
                fileName || url.split("/").pop() || "Attachment File";
              return (
                <a
                  key={
                    attachment.id ||
                    attachment._id ||
                    attachment.public_id ||
                    `att-${message._id}-${index}`
                  }
                  href={url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center p-4 bg-white/90 dark:bg-[#0c1226]/40 border border-slate-200/70 dark:border-white/5 hover:bg-white hover:border-sky-400/40 dark:hover:bg-[#0c1226]/60 dark:hover:border-blue-500/30 rounded-2xl cursor-pointer transition-all min-w-[270px] max-w-xs select-none group text-left backdrop-blur-md"
                >
                  <div className="w-10 h-10 bg-sky-500/10 text-sky-600 dark:text-blue-400 rounded-xl flex items-center justify-center shrink-0">
                    <FiFile size={18} />
                  </div>
                  <div className="ml-3.5 flex-1 overflow-hidden">
                    <p className="text-xs font-bold text-slate-700 dark:text-gray-200 truncate group-hover:text-sky-600 dark:group-hover:text-blue-400 transition-colors">
                      {fileDisplayName}
                    </p>
                    <p className="text-[10px] text-slate-500 dark:text-gray-500 font-bold uppercase tracking-wider mt-0.5">
                      Download File
                    </p>
                  </div>
                  <FiDownload
                    className="text-slate-400 group-hover:text-sky-600 dark:text-gray-400 dark:group-hover:text-blue-400 transition-colors ml-2 shrink-0"
                    size={16}
                  />
                </a>
              );
          }
        })}
      </div>
    );
  };

  const renderBubbleContent = () => {
    const hasMedia =
      (message.mediaUrl && message.mediaType !== "none") || hasAttachments;

    return (
      <div
        className={`flex flex-col gap-2 ${isMine ? "items-end" : "items-start"}`}
      >
        {hasMedia && renderMedia()}
        {!isAutoGeneratedMediaMsg && message.content && (
          <p className="text-[14.5px] leading-relaxed break-words text-left">
            {message.content}
          </p>
        )}
      </div>
    );
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 12, scale: 0.97 }}
      animate={{ opacity: 1, y: 0, scale: 1 }}
      transition={{ duration: 0.3 }}
      className={`flex w-full ${isMine ? "justify-end" : "justify-start"} mb-4`}
    >
      {!isMine && (
        <img
          referrerPolicy="no-referrer"
          src={
            message.sender.profilePicture ||
            "https://icon-library.com/images/anonymous-avatar-icon/anonymous-avatar-icon-25.jpg"
          }
          alt="avatar"
          className="w-9 h-9 rounded-full object-cover mr-3 self-end shadow-md border border-white/5"
        />
      )}
      <div
        className={`flex flex-col max-w-[75%] lg:max-w-[65%] ${isMine ? "items-end" : "items-start"}`}
      >
        {isImageOrVideoOnly ? (
          // Render image/video directly without the bubble container for a premium borderless look
          <div className="relative">{renderMedia()}</div>
        ) : (
          // Render inside a styled chat bubble
          <div
            className={`px-5 py-3.5 shadow-md relative ${
              isMine
                ? "bg-gradient-to-tr from-sky-600 via-blue-600 to-indigo-600 text-white rounded-2xl rounded-tr-sm border border-white/10"
                : "bg-white/90 dark:bg-white/5 backdrop-blur-md text-slate-700 dark:text-gray-200 rounded-2xl rounded-tl-sm border border-slate-200/70 dark:border-white/5"
            }`}
          >
            {renderBubbleContent()}
          </div>
        )}
        <div className="flex items-center gap-1.5 mt-1.5 px-1.5">
          <span className="text-[10px] font-bold text-slate-400 dark:text-gray-500 uppercase tracking-wide">
            {format(new Date(message.createdAt), "hh:mm a")}
          </span>
          {isMine && (
            <svg
              className="w-3.5 h-3.5 text-sky-400"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2.5"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <polyline points="20 6 9 17 4 12"></polyline>
            </svg>
          )}
        </div>
      </div>
    </motion.div>
  );
};

export default MessageBubble;
